language: "go"

go:
  - "1.5.1"
  - "tip"

install:
  - "go get github.com/constabulary/gb/..."
  - "go get golang.org/x/tools/cmd/vet"
  - "go get golang.org/x/lint/golint"
  - "gb build"

script:
  - "go vet ./src/..."
  - "golint ./src/..."
  - "gb test"
